#include "DiskTest.h"

void DiskTest() {
  int x;
  creat("new");
  creat("second");
  creat("test");
  char* emus  = "The emu (Dromaius novaehollandiae) is the second-largest living bird by height, after its ratite relative, the ostrich. It is endemic to Australia where it is the largest native bird and the only extant member of the genus Dromaius. The emu's range covers most of mainland Australia, but the Tasmanian emu and King Island emu subspecies became extinct after the European settlement of Australia in 1788. The bird is sufficiently common for it to be rated as a least-concern species by the International Union for Conservation of Nature.\nEmus are soft-feathered, brown, flightless birds with long necks and legs, and can reach up to 1.9 metres (6.2 ft) in height. Emus can travel great distances, and when necessary can sprint at 50 km/h (30 mph); they forage for a variety of plants and insects, but have been known to go for weeks without eating. They drink infrequently, but take in copious amounts of water when the opportunity arises.\nThe ostrich or common ostrich (Struthio camelus) is either one or two species of large flightless birds native to Africa, the only living member(s) of the genus Struthio, which is in the ratite family. Starting in 2014, the Somali ostrich is now considered a full species separate from the common ostrich.[3]\nThe ostrich shares the order Struthioniformes with the kiwis, emus, rheas and cassowaries. However, phylogenetic studies have shown that it is the basal extant member of Palaeognathae and is thus equally closely related to flighted tinamous.[4][5] It is distinctive in its appearance, with a long neck and legs, and can run at up to about 70 km/h (19 m/s; 43 mph),[6] the fastest land speed of any bird.[7] The ostrich is the largest living species of bird and lays the largest eggs of any living bird (extinct elephant birds of Madagascar and the giant moa of New Zealand laid larger eggs).\n The ostrich's diet consists mainly of plant matter, though it also eats invertebrates. It lives in nomadic groups of 5 to 50 birds. When threatened, the ostrich will either hide itself by lying flat against the ground, or run away. If cornered, it can attack with a kick of its powerful legs. Mating patterns differ by geographical region, but territorial males fight for a harem of two to seven females.\nThe ostrich is farmed around the world, particularly for its feathers, which are decorative and are also used as feather dusters. Its skin is used for leather products and its meat is marketed commercially, with its leanness a common marketing point.[6]\n";
  char* gnus = "The wildebeests, also called gnus or wildebai, are a genus of antelopes, Connochaetes. They belong to the family Bovidae, which includes antelopes, cattle, goats, sheep and other even-toed horned ungulates. Connochaetes includes two species, both native to Africa: the black wildebeest, or white-tailed gnu (C. gnou); and the blue wildebeest, or brindled gnu (C. taurinus). Fossil records suggest these two species diverged about one million years ago, resulting in a northern and a southern species. The blue wildebeest remained in its original range and changed very little from the ancestral species, while the black wildebeest changed more in order to adapt to its open grassland habitat in the south. The most obvious way of telling the two species apart are the differences in their colouring and in the way their horns are oriented.\nIn East Africa, the blue wildebeest is the most abundant big game species and some populations perform an annual migration to new grazing grounds but the black wildebeest is merely nomadic. Wildebeest often graze in mixed herds with zebra which gives heightened awareness of potential predators. They are also alert to the warning signals emitted by other animals such as baboons. Wildebeest are a tourist attraction but compete with domesticated livestock for pasture and are sometimes blamed by farmers for transferring diseases and parasites to their cattle. Some illegal hunting goes on but the population trend is fairly stable and some populations are in national parks or on private land. The IUCN lists both species as being of least concern.\n";
  char* penguins  = "Penguins (order Sphenisciformes, family Spheniscidae) are a group of aquatic, flightless birds living almost exclusively in the Southern Hemisphere, especially in Antarctica. Highly adapted for life in the water, penguins have countershaded dark and white plumage, and their wings have evolved into flippers. Most penguins feed on krill, fish, squid and other forms of sealife caught while swimming underwater. They spend about half of their lives on land and half in the oceans.\nAlthough all penguin species are native to the Southern Hemisphere, they are not found only in cold climates, such as Antarctica. In fact, only a few species of penguin live so far south. Several species are found in the temperate zone, and one species, the Galápagos penguin, lives near the equator.\nThe largest living species is the emperor penguin (Aptenodytes forsteri): on average adults are about 1.1 m (3 ft 7 in) tall and weigh 35 kg (77 lb) or more. The smallest penguin species is the little blue penguin (Eudyptula minor), also known as the fairy penguin, which stands around 40 cm (16 in) tall and weighs 1 kg (2.2 lb). Among extant penguins, larger penguins inhabit colder regions, while smaller penguins are generally found in temperate or even tropical climates (see also Bergmann's rule). Some prehistoric species attained enormous sizes, becoming as tall or as heavy as an adult human. These were not restricted to Antarctic regions; on the contrary, subantarctic regions harboured high diversity, and at least one giant penguin occurred in a region not quite 2,000 km south of the equator 35 mya, in a climate decidedly warmer than today.";
  char* bats   = "Bats are mammals of the order Chiroptera (/kaɪˈrɒptərə/; from the Greek χείρ - cheir, \"hand\"[1] and πτερόν - pteron, \"wing\"[2]) whose forelimbs form webbed wings, making them the only mammals naturally capable of true and sustained flight. By contrast, other mammals said to fly, such as flying squirrels, gliding possums, and colugos, can only glide for short distances. Bats do not flap their entire forelimbs, as birds do, but instead flap their spread-out digits,[3] which are very long and covered with a thin membrane or patagium.\nBats are the second largest order of mammals (after the rodents), representing about 20% of all classified mammal species worldwide, with about 1,240 bat species divided into two suborders: the less specialized and largely fruit-eating megabats, or flying foxes, and the highly specialized and echolocating microbats.[4] About 70% of bat species are insectivores. Most of the rest are frugivores, or fruit eaters. A few species, such as the fish-eating bat, feed from animals other than insects, with the vampire bats being hematophagous, or feeding on blood.\nBats are present throughout most of the world, with the exception of extremely cold regions. They perform the vital ecological roles of pollinating flowers and dispersing fruit seeds; many tropical plant species depend entirely on bats for the distribution of their seeds. Bats are economically important, as they consume insect pests, reducing the need for pesticides. The smallest bat is the Kitti's hog-nosed bat, measuring 29–34 mm (1.14–1.34 in) in length, 15 cm (5.91 in) across the wings and 2–2.6 g (0.07–0.09 oz) in mass.[5][6] It is also arguably the smallest extant species of mammal, with the Etruscan shrew being the other contender.[7] The largest species of bat are a few species of Pteropus (fruit bats or flying foxes) and the giant golden-crowned flying fox with a weight up to 1.6 kg (4 lb) and wingspan up to 1.7 m (5 ft 7 in).\n";
  int fd;
  fd = open("second",O_WR);
  write(fd,emus,strlen(emus));
  close(fd);
  fd = open("test",O_RDWR);
  write(fd,gnus,strlen(gnus));
  close(fd);
  fd = open("second",O_RD);
  lseek(fd,strlen(emus),SEEK_R);
  write(fd,penguins,strlen(penguins));
  close(fd);
  fd = open("second",O_WR);
  lseek(fd,strlen(emus),SEEK_R);
  write(fd,bats,strlen(bats));
  close(fd);
  fd = open("second",O_RDWR);
  char str[34000];
  x = read(fd,str,33000);
  printf("%d\n",x);
  str[x] = '\0';
  printf(str);
  while( 1 ) {
  }

  return;
}

void (*entry_DiskTest)() = &DiskTest;
